ETH:
  outputs:
    dev:
      account: QMZETXK-JN51440
      database: ETH
      role: ACCOUNTADMIN
      schema: ETH_DEV
      threads: 4
      type: snowflake
      user: vodro
      password: Vodounon1234@!
      warehouse: COMPUTE_WH
  target: dev
