version: 2

sources:
  - name: eth
    database: eth
    schema: eth
    tables:
      - name: ETH_TRANSACTIONS_RAW
        description: "Raw Ethereum transactions data ingested from external source."
        freshness:
          warn_after: {count: 1, period: hour}
          error_after: {count: 22, period: hour}
        loaded_at_field: to_timestamp(payload:block_timestamp)